name: dropbox_example
description: Demonstrates how to use the dropbox plugin.
publish_to: 'none'
version: 1.2.0

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  dropbox_client:
    path: ../

flutter:
  uses-material-design: true
